### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by mithuncoder** [Nico-Curti/pyhide#1]
G:\admin>pyhide --input test.py --output he.py
'pyhide' is not recognized as an internal or external command,
operable program or batch file.

i installed pyhide using pip..but showing this error

**Comment by Nico-Curti** [comment]
I have not loaded the package on Pypi yet so for the installation you need to use the local setup.py file, using the command

```bash
python -m pip install --editable . --user
```

After the package installation you should find the pyhide program in your path

**Comment by john-whick-13** [comment]
can you explain more how to setup the package using setup file

**Comment by john-whick-13** [comment]
i install it but get this error 

UnboundLocalError: cannot access local variable 'bomb' where it is not associated with a value

pyhide --input myfile.py --output out.py

**Comment by Nico-Curti** [comment]
I temporary removed the documentation about pip and conda since I want to improve some details before the upload on Pypi.
There are no official release of the package now, so the only way in which you can install the package is via setup command as described in the README and in my previous comment

**Comment by Nico-Curti** [comment]
I close this issue as the installation error has been solved using the setup and the documentation has been changed accordingly.
Feel free to reopen it if the error persists.
